/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg7_jamilgarcia;

import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JamilGarcía
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_MiUnidad = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_MiUnidad = new javax.swing.JList<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jl_Name = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_descargado = new javax.swing.JList<>();
        jpop_MiUnidad = new javax.swing.JPopupMenu();
        Favorito = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Descargar = new javax.swing.JMenuItem();
        Agregar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        b_MiUnidad = new javax.swing.JButton();
        b_Destacados = new javax.swing.JButton();
        b_Papelera = new javax.swing.JButton();
        b_Agregar = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();

        jl_MiUnidad.setModel(new DefaultListModel());
        jl_MiUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_MiUnidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_MiUnidad);

        jProgressBar1.setMaximum(3);
        jProgressBar1.setToolTipText("");
        jProgressBar1.setName(""); // NOI18N

        jButton1.setText("<-");

        jl_Name.setText("dive.google.com/MiUnidad");

        jLabel2.setText("Descargando:");

        jl_descargado.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_descargado);

        javax.swing.GroupLayout jf_MiUnidadLayout = new javax.swing.GroupLayout(jf_MiUnidad.getContentPane());
        jf_MiUnidad.getContentPane().setLayout(jf_MiUnidadLayout);
        jf_MiUnidadLayout.setHorizontalGroup(
            jf_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MiUnidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jf_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_MiUnidadLayout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(jl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_MiUnidadLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(jf_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jf_MiUnidadLayout.setVerticalGroup(
            jf_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MiUnidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jf_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jf_MiUnidadLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jl_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jf_MiUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jf_MiUnidadLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 294, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Favorito.setText("Favorito");
        Favorito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FavoritoMouseClicked(evt);
            }
        });
        Favorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavoritoActionPerformed(evt);
            }
        });
        jpop_MiUnidad.add(Favorito);

        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jpop_MiUnidad.add(Eliminar);

        Descargar.setText("Descargar");
        Descargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescargarMouseClicked(evt);
            }
        });
        Descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargarActionPerformed(evt);
            }
        });
        jpop_MiUnidad.add(Descargar);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jpop_MiUnidad.add(Agregar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU");

        b_MiUnidad.setText("Mi Unidad");
        b_MiUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_MiUnidadMouseClicked(evt);
            }
        });

        b_Destacados.setText("Destacados");
        b_Destacados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_DestacadosMouseClicked(evt);
            }
        });

        b_Papelera.setText("Papelera");
        b_Papelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_PapeleraMouseClicked(evt);
            }
        });

        b_Agregar.setText("Agregar");
        b_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_AgregarMouseClicked(evt);
            }
        });

        jProgressBar2.setMaximum(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_Destacados)
                            .addComponent(b_MiUnidad)
                            .addComponent(b_Papelera)
                            .addComponent(b_Agregar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(b_MiUnidad)
                .addGap(18, 18, 18)
                .addComponent(b_Destacados)
                .addGap(18, 18, 18)
                .addComponent(b_Papelera)
                .addGap(18, 18, 18)
                .addComponent(b_Agregar)
                .addGap(33, 33, 33)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_MiUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_MiUnidadMouseClicked
        // TODO add your handling code here:
        AdminMiUnidad am = new AdminMiUnidad("./miunidad.tcr");
        AdminDestacados ad = new AdminDestacados("./destacados.tcr");
        AdminPapelera ap = new AdminPapelera("./papelera.tcr");
        am.cargarArchivo();
        am.setListaMiUnidad(MiUnidad);
        am.escribirArchivo();
        ad.cargarArchivo();
        ad.setListaMiUnidad(Destacados);
        ad.escribirArchivo();
        ap.cargarArchivo();
        ap.setListaMiUnidad(Papelera);
        ap.escribirArchivo();
        jf_MiUnidad.setVisible(true);
        DefaultListModel lista = (DefaultListModel) jl_MiUnidad.getModel();
        lista.clear();
        for (int i = 0; i < MiUnidad.size(); i++) {
            lista.addElement(MiUnidad.get(i));
        }
        jl_MiUnidad.setModel(lista);
        linkGlo = "dive.google.com/MiUnidad";
    }//GEN-LAST:event_b_MiUnidadMouseClicked

    private void b_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_AgregarMouseClicked
        // TODO add your handling code here:
        int opcion;
        Carpeta carpet;
        Archivo archiv;
        opcion = Integer.parseInt(JOptionPane.showInputDialog("Desea crear: \n 1 Carpeta \n 2 Archivo"));
        if (opcion == 1) {
            carpet = CrearCarpet();
            MiUnidad.add(carpet);
        } else if (opcion == 2) {
            archiv = CrearArchiv();
            MiUnidad.add(archiv);
        }
        AdministrarBarra ab = new AdministrarBarra(jProgressBar2, 2);
        ab.start();
        AdminMiUnidad am = new AdminMiUnidad("./miunidad.tcr");
        AdminDestacados ad = new AdminDestacados("./destacados.tcr");
        AdminPapelera ap = new AdminPapelera("./papelera.tcr");
        am.cargarArchivo();
        am.setListaMiUnidad(MiUnidad);
        am.escribirArchivo();
        ad.cargarArchivo();
        ad.setListaMiUnidad(Destacados);
        ad.escribirArchivo();
        ap.cargarArchivo();
        ap.setListaMiUnidad(Papelera);
        ap.escribirArchivo();
    }//GEN-LAST:event_b_AgregarMouseClicked

    private void jl_MiUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_MiUnidadMouseClicked
        // TODO add your handling code here:

        if (evt.isMetaDown()) {
            jpop_MiUnidad.show(evt.getComponent(),
                    evt.getX(), evt.getY());
        } else if (evt.getClickCount() == 2) {
            int flag = jl_MiUnidad.getSelectedIndex();
            AdministrarBarra ab = new AdministrarBarra(jProgressBar1, 3);
            ab.start();
            ArrayList<Carpeta> temp = new ArrayList();
            DefaultListModel lista = (DefaultListModel) jl_MiUnidad.getModel();
            for (int i = 0; i < lista.size(); i++) {
                temp.add((Carpeta) lista.get(i));
            }
            lista.clear();
            for (int i = 0; i < temp.get(flag).getLista().size() - 1; i++) {
                lista.addElement(temp.get(flag).getLista().get(i));
            }
            linkGlo += "/" + temp.get(flag).getLink();
            jProgressBar1.setName(linkGlo);
            jl_Name.setText(linkGlo);
            jl_MiUnidad.setModel(lista);
        }
        AdminMiUnidad am = new AdminMiUnidad("./miunidad.tcr");
        AdminDestacados ad = new AdminDestacados("./destacados.tcr");
        AdminPapelera ap = new AdminPapelera("./papelera.tcr");
        am.cargarArchivo();
        am.setListaMiUnidad(MiUnidad);
        am.escribirArchivo();
        ad.cargarArchivo();
        ad.setListaMiUnidad(Destacados);
        ad.escribirArchivo();
        ap.cargarArchivo();
        ap.setListaMiUnidad(Papelera);
        ap.escribirArchivo();

    }//GEN-LAST:event_jl_MiUnidadMouseClicked

    private void FavoritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FavoritoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_FavoritoMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_EliminarMouseClicked

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        int opcion, flag = jl_MiUnidad.getSelectedIndex();
        Carpeta carpet;
        Archivo archiv;
        opcion = Integer.parseInt(JOptionPane.showInputDialog("Desea crear: \n 1 Carpeta \n 2 Archivo"));
        if (opcion == 1) {
            carpet = CrearCarpet();
            ((Carpeta) MiUnidad.get(flag)).getLista().add(carpet);
            JOptionPane.showMessageDialog(this, "Accion con exito");
        } else if (opcion == 2) {
            archiv = CrearArchiv();
            ((Carpeta) MiUnidad.get(flag)).getLista().add(archiv);
            JOptionPane.showMessageDialog(this, "Accion con exito");
        }
        DefaultListModel lista = (DefaultListModel) jl_MiUnidad.getModel();
        lista.clear();
        for (int i = 0; i < MiUnidad.size(); i++) {
            lista.addElement(MiUnidad.get(i));
        }
        jl_MiUnidad.setModel(lista);
        AdminMiUnidad am = new AdminMiUnidad("./miunidad.tcr");
        AdminDestacados ad = new AdminDestacados("./destacados.tcr");
        AdminPapelera ap = new AdminPapelera("./papelera.tcr");
        am.cargarArchivo();
        am.setListaMiUnidad(MiUnidad);
        am.escribirArchivo();
        ad.cargarArchivo();
        ad.setListaMiUnidad(Destacados);
        ad.escribirArchivo();
        ap.cargarArchivo();
        ap.setListaMiUnidad(Papelera);
        ap.escribirArchivo();
    }//GEN-LAST:event_AgregarActionPerformed

    private void b_DestacadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_DestacadosMouseClicked
        jf_MiUnidad.setVisible(true);
        DefaultListModel lista = (DefaultListModel) jl_MiUnidad.getModel();
        lista.clear();
        for (int i = 0; i < Destacados.size(); i++) {
            lista.addElement(Destacados.get(i));
        }
        jl_MiUnidad.setModel(lista);
        linkGlo = "dive.google.com/Destacados";
    }//GEN-LAST:event_b_DestacadosMouseClicked

    private void b_PapeleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_PapeleraMouseClicked
        jf_MiUnidad.setVisible(true);
        DefaultListModel lista = (DefaultListModel) jl_MiUnidad.getModel();
        lista.clear();
        for (int i = 0; i < Papelera.size(); i++) {
            lista.addElement(Papelera.get(i));
        }
        jl_MiUnidad.setModel(lista);
        linkGlo = "dive.google.com/Papelera";
    }//GEN-LAST:event_b_PapeleraMouseClicked

    private void DescargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescargarMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_DescargarMouseClicked

    private void FavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritoActionPerformed
        // TODO add your handling code here:
        int flag = jl_MiUnidad.getSelectedIndex();
        ArrayList<Carpeta> temp = new ArrayList();
        DefaultListModel lista = (DefaultListModel) jl_MiUnidad.getModel();
        Destacados.add(lista.get(flag));
        MiUnidad.remove(lista.get(flag));
        lista.remove(flag);
        jl_MiUnidad.setModel(lista);
        System.out.println("hecho");
        AdminMiUnidad am = new AdminMiUnidad("./miunidad.tcr");
        AdminDestacados ad = new AdminDestacados("./destacados.tcr");
        AdminPapelera ap = new AdminPapelera("./papelera.tcr");
        am.cargarArchivo();
        am.setListaMiUnidad(MiUnidad);
        am.escribirArchivo();
        ad.cargarArchivo();
        ad.setListaMiUnidad(Destacados);
        ad.escribirArchivo();
        ap.cargarArchivo();
        ap.setListaMiUnidad(Papelera);
        ap.escribirArchivo();
    }//GEN-LAST:event_FavoritoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int flag = jl_MiUnidad.getSelectedIndex();
        ArrayList<Carpeta> temp = new ArrayList();
        DefaultListModel lista = (DefaultListModel) jl_MiUnidad.getModel();
        Papelera.add(lista.get(flag));
        MiUnidad.remove(lista.get(flag));
        lista.remove(flag);
        jl_MiUnidad.setModel(lista);
        AdminMiUnidad am = new AdminMiUnidad("./miunidad.tcr");
        AdminDestacados ad = new AdminDestacados("./destacados.tcr");
        AdminPapelera ap = new AdminPapelera("./papelera.tcr");
        am.cargarArchivo();
        am.setListaMiUnidad(MiUnidad);
        am.escribirArchivo();
        ad.cargarArchivo();
        ad.setListaMiUnidad(Destacados);
        ad.escribirArchivo();
        ap.cargarArchivo();
        ap.setListaMiUnidad(Papelera);
        ap.escribirArchivo();
    }//GEN-LAST:event_EliminarActionPerformed

    private void DescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargarActionPerformed
        // TODO add your handling code here:
        DefaultListModel listaDescar = (DefaultListModel) jl_descargado.getModel();
        DefaultListModel lista = (DefaultListModel) jl_MiUnidad.getModel();
        int flag = jl_MiUnidad.getSelectedIndex();
        if (lista.get(flag) instanceof Archivo) {
            int limit = (((Archivo) lista.get(flag)).getTamaño()) / 10;
            jProgressBar3.setMaximum(limit);
            AdministrarBarra ab = new AdministrarBarra(jProgressBar3, limit);
            ab.start();
            listaDescar.addElement(lista.get(flag));
        } else {
            for (int i = 0; i < lista.getSize(); i++) {
                if (((Carpeta) lista.get(flag)).getLista().get(i) instanceof Archivo) {
                    Archivo limi = (Archivo) ((Carpeta) lista.get(flag)).getLista().get(i);
                    int limit = limi.getTamaño();
                    jProgressBar3.setMaximum(limit);
                    AdministrarBarra ab = new AdministrarBarra(jProgressBar3, limit);
                    ab.start();
                    listaDescar.addElement(lista.get(flag));
                }
            }
        }
        jl_descargado.setModel(listaDescar);

    }//GEN-LAST:event_DescargarActionPerformed

    public void ProgressBar() {

    }

    ;
    
    public Carpeta CrearCarpet() {
        String nombre = "", link, extension;
        int tamaño;
        Carpeta temp;

        nombre = JOptionPane.showInputDialog("Ingrese el nombre de la carpeta: ");
        link = "";
        for (int i = 0; i < 5; i++) {
            link += (char) (97 + r.nextInt(25));
        }

        temp = new Carpeta(nombre, link);
        return temp;
    }

    ;
    
    public Archivo CrearArchiv() {
        String nombre = "", link = "", extension;
        int tamaño;
        Archivo temp;

        nombre = JOptionPane.showInputDialog("Ingrese el nombre del archivo: ");
        extension = JOptionPane.showInputDialog("Ingrese la extension: \n"
                + "1 .pdf \n"
                + "2 .txt \n"
                + "3 .docx \n"
                + "4 .jpg \n"
                + "5 .mp4 \n");
        if (extension.equals("1")) {
            extension = ".pdf";
        } else if (extension.equals("2")) {
            extension = ".txt";
        } else if (extension.equals("3")) {
            extension = ".docx";
        } else if (extension.equals("4")) {
            extension = ".jpg";
        } else if (extension.equals("5")) {
            extension = ".mp4";
        } else {
            extension = ".null";
            JOptionPane.showMessageDialog(this, "Algo paso en las extensiones, se asignara como .null");
        }

        tamaño = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el tamaño del archivo: "));
        for (int i = 0; i < 10; i++) {
            link += (char) (97 + r.nextInt(25));
        }
        temp = new Archivo(nombre, link, extension, tamaño);
        return temp;
    }

    ;
    
    public void GuardarTodo() {

    }

    ;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JMenuItem Descargar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Favorito;
    private javax.swing.JButton b_Agregar;
    private javax.swing.JButton b_Destacados;
    private javax.swing.JButton b_MiUnidad;
    private javax.swing.JButton b_Papelera;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFrame jf_MiUnidad;
    private javax.swing.JList<String> jl_MiUnidad;
    private javax.swing.JLabel jl_Name;
    private javax.swing.JList<String> jl_descargado;
    private javax.swing.JPopupMenu jpop_MiUnidad;
    // End of variables declaration//GEN-END:variables
    ArrayList MiUnidad = new ArrayList();
    ArrayList Destacados = new ArrayList();
    ArrayList Papelera = new ArrayList();
    ArrayList Descargando = new ArrayList();
    ArrayList Descargado = new ArrayList();
    Random r = new Random();
    Carpeta temporal;
    String linkGlo;

}
